; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27024.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\REDhql\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
